spring:
  application:
    name: tollrate-service
  devtools:
    livereload:
      enabled: true

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
    hostname: localhost

security:
  basic:
    enabled: false

management:
  security:
    enabled: false


