spring:
  application:
    name: eureka-server
  devtools:
    livereload:
      enabled: true

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
